### PR TITLE
Multiple new functions

### PR DESCRIPTION
**Pull request by fradav**
New functions :

prod
prod_red
cum_prod
filter_out_seq
index_of_seq
permute
sort
sort_index

### CODE REVIEW

**Comment by fradav** [comment]
Hello,

We are a team working on a linear algebra library for gpu [keops](https://github.com/getkeops/keops) and we searched for a "light" c++14 tmp library working on sequences for a generic [tensordot](https://docs.scipy.org/doc/numpy-1.14.0/reference/generated/numpy.tensordot.html) operator. `boost::hana` wouldn't do (too heavy and relying on boost), but `tao::seq` quite easily fitted the bill. In the meantime we added some functions we needed, and backported them in the `tao::seq`, that's why the PR.

Regards,

**Comment by d-frey** [comment]
Thank you, I'll consider adding those things but I'll do it step by step. There are a few things that will come up while doing so:

a) Some things can already be implemented with existing facilities, e.g. `prod` can be implemented using `zip`.
b) Recursion. Some of your implementations use recursion, but one of the main points of this library (and what makes it efficient wrt compile-time) is *avoiding* recursion. I'll see what can/should be done about this.
c) Naming. In the context of the STL, we already have `plus` and `multiply`, so I renamed `prod` to `multiply`.

I'll start with adding `multiply` and, after each step, one needs to monitor the CI as your code triggered an ICE in one compiler (and only with C++17).

I'll let you know when I have specific questions later.

**Comment by d-frey** [comment]
Current status:

- [x]  `prod` ➙ `multiply` (similar to the existing `plus`)
- [x]  `prod_red` ➙ `prod` (similar to the existing `sum`)
- [ ] `cum_prod`
- [x] `index_of_seq`
- [x] `filter_out_seq` ➙ `difference` (similar to the standard library's `set_difference`)
- [x] `permute` ➙ `permutate`
- [x] `sort`
- [x] `sort_index`

**Comment by fradav** [comment]
Hello,

Thanks you very much for your integration work! 
I'm totally helpless to debug the ICE error at this point, sorry.
As a side question do you have any sources/papers/benchmarks about any benefit in compile times in sequential vs recursive implementations with tmp ? 

Regards

**Comment by fradav** [comment]
cum_prod is inspired from the [matlab's one](https://www.mathworks.com/help/matlab/ref/cumprod.html) and is simply a scan on multiply.
I think it would be interesting to get an optimized and generic (exclusive/inclusive) scan, as you did already with fold. Currently it computes partial_sum for each step. 

Regards.

**Comment by d-frey** [comment]
Don't worry about the ICE, the way I implemented things it is fixed already. Plus I added MSVC 2019 to the CI and then fixed what they screwed up :)

For the benefits of avoiding recursion, please see https://github.com/taocpp/tuple/blob/master/Variadic%20Templates.pdf

It's a long set of slides, but starting at slide 58 you can see the benchmarks. It can be an order of magnitude faster to avoid recursion. You could also compare your version of `sort` with the one I now implemented - mine avoids it at some places (`merge` can only be linear, but the rest can be improved) and you'll find that it is more than 10x faster to compile.

**Comment by d-frey** [comment]
About the current state:

I'm happy with the implementation and semantics of `multiply`, `prod`, `difference` and `sort`. Those are good additions, they have clear semantics and are generally useful.

For `index_of_seq`, I'm slightly unhappy about the name but can't come up with a better one. But the real issue is duplicates. `index_of` returns the *first* matching index, hence `index_of_seq` might not always yield what you think or intend.

This, of course, also affects everything based on `index_of_seq`, namely `sort_index` and `permutate`. For the latter, I struggle with the name as well, again.

For `cum_prod`, I am confused about the reversal (which is not reflected in the name) as well as the semantics. Your testcase maps ( 4, 5, 6, 7 ) to ( 210, 42, 7, 1 ) - which I find suspicious. Even if you reverse the order, shouldn't the result be ( 840, 210, 42, 7 )?

**Comment by fradav** [comment]
Hi again, 

Thanks you very much for the slides, if you don't mind I'd like to show them to my students.

The reverse order in cum_prod is a mistake, something I forgot about: it was a function tailored for tensordot and I was too lazy to do something like `reverse(cum_prod(reverse))`. 

Otherwise this is the same as the exclusive product described [there](https://en.cppreference.com/w/cpp/algorithm/exclusive_scan)

Example ([Godbolt link](https://godbolt.org/z/Rvx3nX)): 

```cpp
#include <functional>
#include <iostream>
#include <iterator>
#include <numeric>
#include <vector>
 
int main()
{
  std::vector data {7, 6, 5, 4};
  
  std::cout << "\n\nexclusive product: ";  
  std::exclusive_scan(data.begin(), data.end(),
		      std::ostream_iterator<int>(std::cout, " "),
		      1, std::multiplies<>{});		      
  std::cout << "\ninclusive product: ";
}
```

I'm very happy to have this exchange with you, I feel a little less alone (I'm the only "expert" c++ developper in my lab...) 

Regards,

**Comment by d-frey** [comment]
Feel free to show the slides to your students, the more people get educated about this, the better :) I still think there was some kind of a historic accident where people doing TMP were comparing it with functional programming. The problem is: In FP, recursion is often the efficient way to implement things - in TMP it is not.

Your explanation on cum_prod being just `std::exclusive_scan` also helps me: I now know that I simply have to improve the existing `tao::seq::exclusive_scan` to allow specifying the operation to use (and probably the neutral element of that operation). The rest should then be very easy to build. Give me a couple of days :)

**Comment by fradav** [comment]
There is one thing which could qualify tmp as FP friendly: tail recursion. I was under the impression that every major compiler had it for tmp, but now I'm not so sure anymore in the light of what you just told me.

--
F.-D.

________________________________

**Comment by d-frey** [comment]
Tail recursion for template meta-programming can not really exist. The problem is memoization, the compiler needs to remember each instantiation and that will blow up memory consumption, which is really bad for performance. Also, look-up of existing instantiation becomes slower. The key to fast TMP is avoiding instantiations, hence using type aliases over real types, using shallow instantiation hierarchies, etc. You might get away with something similar to tail recursion when you only use type alias in the recursion or when you can leverage constexpr functions.

**Comment by fradav** [comment]
> You might get away with something similar to tail recursion when you only use type alias in the recursion or when you can leverage constexpr functions.

I'm not sure to understand this, could you explain with a short example using type alias to "mimick" tail recursion ? And why constexpr could achieve this also, is this permitted only by C++17 constexpr ?

Regards,

**Comment by d-frey** [comment]
The first technique can be seen in https://github.com/taocpp/sequences/blob/master/include/tao/seq/make_integer_sequence.hpp

Notice how `generate` only has four instantiations and `f` is only a type alias, so no matter how many intermediate types are generated from this and how many variadic non-type template parameters they have, they are not instantiated.

The second technique can be seen in https://github.com/taocpp/sequences/blob/master/include/tao/seq/fold.hpp

It seems way easier (i.e. more efficient) for the compiler to go through a `constexpr` function rather than instantiating a type.

As usual, benchmark those things yourself to get a better idea about compile-time efficiency (and watch your compiler's memory usage).

**Comment by fradav** [comment]
Hello again,

Thanks for all your work, we included your changes in our code, but we have a small problem with the  `difference` function and nvcc compiler, we got this strange error: 
` error: mismatched argument pack lengths while expanding ‘tao::seq::impl::conditional_t<typename tao::seq::impl::contains<typename std::common_type<TA, TB>::type>::type<As, Bs>::value, std::integer_sequence<typename std::common_type<TA, TB>::type>, std::integer_sequence<typename std::common_type<TA, TB>::type, As> >’`

If I revert to recursive instead of folding, the error is gone as there:

```cpp
namespace tao
{
   namespace seq
   {
     namespace impl 
     {
         template< typename, typename, typename >
         struct difference_fix;

         template< typename T, T... As >
         struct difference_fix< T, integer_sequence< T >, integer_sequence< T, As... > >
         {
            using type = integer_sequence< T >;
         };

         template< typename T, T... As, T b, T... Bs >
         struct difference_fix< T, integer_sequence< T, b, Bs... >, integer_sequence< T, As... > >
         {
            constexpr static bool included = tao::seq::contains< T, b, As... >::value;
            using tail = typename difference_fix< T, integer_sequence< T, Bs... >, integer_sequence< T, As... > >::type;
            using type = typename std::conditional<
               included,
               tail,
               typename tao::seq::concatenate< integer_sequence< T, b >, tail >::type >::type;
         };

      }  // namespace impl

      template< typename, typename >
      struct difference_fix;

      template< typename TA, TA... As, typename TB, TB... Bs >
      struct difference_fix< integer_sequence< TA, As... >, integer_sequence< TB, Bs... > >
      {
        using CT = typename std::common_type< TA, TB >::type;

         template< CT N >
         using check = contains< CT, N, Bs... >;

        // ERROR THERE
        // using type = concatenate_t< impl::conditional_t< check< As >::value, integer_sequence< CT >, integer_sequence< CT, As > >... >;
        // OK
        using type = typename impl::difference_fix< CT, integer_sequence< CT, As... >, integer_sequence< CT, Bs... > >::type; // ERROR
      };

      template< typename A, typename B >
      using difference_fix_t = typename difference_fix< A, B >::type;

   }  // namespace seq

}  // namespace tao
```

I'm inclined to think this is a compiler bug, but do you have any idea how to circumvent this ?

Regards

**Comment by d-frey** [comment]
Strange, given that `nvcc` is apparently `llvm`-based. I have no experience with `nvcc`, so I can only guess. Maybe something like

```c++
namespace tao
{
   namespace seq
   {
      template< typename, typename >
      struct difference;

      template< typename TA, TA... As, typename TB, TB... Bs >
      struct difference< integer_sequence< TA, As... >, integer_sequence< TB, Bs... > >
      {
         using CT = typename std::common_type< TA, TB >::type;

         template< CT N >
         using check = contains< CT, N, Bs... >;

         template< CT A >
         using apply = impl::conditional_t< check< A >::value, integer_sequence< CT >, integer_sequence< CT, A > >;

         using type = concatenate_t< apply< As >... >;
      };

      template< typename A, typename B >
      using difference_t = typename difference< A, B >::type;

   }  // namespace seq

}  // namespace tao
```

might help? Or you could try and create a PR adding a CI-job for CUDA/`nvcc`, if the required changes are reasonable I'd accept the PR and we could support it better in the future.

**Comment by d-frey** [comment]
Since most of the requested additions were added, I'm closing this PR.

**Pull request closed without merging**
