### PR TITLE
Add contains

### PR DESCRIPTION
**Pull request by mvslobbe**
A simple addition to check whether a value exists in the sequence..

### CODE REVIEW

**Comment by mvslobbe** [comment]
I will revisit this later, once I amend the readme too. Please ignore.

**Comment by d-frey** [comment]
I implemented a proper version of `contains`, please have a look.

Some notes:

a) Do you have any actual use-case for `contains`? I'd be interested to hear about it.
b) Your interface for `contains` was not as generic as the rest of the library. See the new tests I added.
c) The whole point of this repository is to *avoid* recursion. Please also see [this presentation](https://github.com/taocpp/tuple/blob/master/Variadic%20Templates.pdf).

**Comment by mvslobbe** [comment]
Ah, I hadn't seen the presentation. That explains a lot about the design; thanks for that!

As for my use case; I'm using `contains` within a `static_assert` to give me a compile error that's somewhat user-friendly when I'm using my custom rolled `index_of<sequence, value>` helper function on a value that isn't in the sequence.

I'll read your presentation more carefully as I'm sure they would improve more of my custom helper functions. Specifically, I'll try my hand at improving this `index_of` function to the point where it would make for a good pull request ;)

**Comment by d-frey** [comment]
I couldn't resist to try it myself, committed now. You can try to roll your own before looking at it ;)

The key is, of course, to re-use existing facilities instead of manually rolling your own complete implementation.

**Pull request closed without merging**
